### ISSUE TITLE
usage of this lib

### ISSUE THREAD

**Issue by nathanCodeLife** [VerifAPS/verifaps-lib#16]
i wonder what does this lib exactly analysis ?  syntax error？
And how to use it？

**Comment by wadoon** [comment]
This library offers functions for *formal verification* of IEC 61131 programs. 

The (main) pipeline allows to read software written in Structured Text (and Sequential Function Charts and Function Block Diagrams and Instruction List), bring it into a normalised intermediate representation (called ST0 internally) and translate it into the SMV input format for nuXmv/nuSMV. This allows you to check your software against formal properties expressed in a temporal logic (LTL, CTL, PSL). 

On top of that the library a lot of analyses have been implemented, e.g. (modular) regression verification, generalised test tables, relational test tables, verification of information forgetting, etc. Refer to the publications (just the tip of the iceberg):

* Alexander Weigl, Mattias Ulbrich, Suhyun Cha, Bernhard Beckert, Birgit Vogel-Heuser:
Relational Test Tables: A Practical Specification Language for Evolution and Security. FormaliSE@ICSE 2020: 77-86
* Alexander Weigl, Mattias Ulbrich, Daniel Lentzsch:
Modular Regression Verification for Reactive Systems. ISoLA (2) 2020: 25-43
* Bernhard Beckert, Jakob Mund, Mattias Ulbrich, Alexander Weigl:
Formal Verification of Evolutionary Changes. Managed Software Evolution 2019: 309-332

For usage, the best way is to track down one of the main-methods. I can easily state whether the library is usable for you, if you tell your application scenario.
